// English Response Messages
module.exports = {
  AUTH: {
    REGISTER_SUCCESS: "User registered successfully",
    LOGIN_SUCCESS: "Login successful",
    LOGOUT_SUCCESS: "Logout successful",
    PROFILE_RETRIEVED: "Profile retrieved successfully",
    PROFILE_UPDATED: "Profile updated successfully",
    PASSWORD_CHANGED: "Password changed successfully",
    INVALID_CREDENTIALS: "Invalid email or password",
    EMAIL_ALREADY_EXISTS: "Email already exists",
    ACCOUNT_DEACTIVATED: "Account is deactivated. Please contact administrator.",
    VALIDATION_ERROR: "Validation error",
    ROLE_REQUIRED: "Role is required",
    PASSWORD_TOO_SHORT: "Password must be at least 8 characters long",
    PASSWORD_MUST_DIFFER: "New password must be different from current password",
    CURRENT_PASSWORD_INCORRECT: "Current password is incorrect",
    USER_NOT_FOUND: "User not found",
    CANNOT_REGISTER_AS_ADMIN: "Cannot register as admin",
    EMAIL_PASSWORD_REQUIRED: "Email and password are required",
  },
  COMMON: {
    SUCCESS: "Operation successful",
    CREATED: "Resource created successfully",
    UPDATED: "Resource updated successfully",
    DELETED: "Resource deleted successfully",
    NOT_FOUND: "Resource not found",
    UNAUTHORIZED: "Unauthorized access",
    FORBIDDEN: "Access forbidden",
    INTERNAL_SERVER_ERROR: "Internal server error",
    VALIDATION_ERROR: "Validation error",
    INVALID_TOKEN: "Invalid or expired token",
  },
};
