// Schedule Response Messages
module.exports = {
  en: {
    GENERATED: "Schedules generated successfully",
    UPDATED: "Schedule updated successfully",
    DELETED: "Schedule deleted successfully",
    BULK_DELETED: "All schedules for course deleted successfully",
    NOT_FOUND: "Schedule not found",
    LIST_SUCCESS: "Schedules retrieved successfully",
    DETAIL_SUCCESS: "Schedule details retrieved successfully",
    COURSE_NOT_FOUND: "Course not found for schedule generation",
    TEACHER_SCHEDULE_SUCCESS: "Teacher schedule retrieved successfully",
    INVALID_WEEK_DAYS: "Invalid week days provided",
    INVALID_TIME_RANGE: "Start time must be before end time",
    NO_SCHEDULES_GENERATED: "No schedules generated - check date range and week days",
    TEACHER_PERMISSION_DENIED: "You can only update schedules for courses you teach",
    SUBSTITUTE_TEACHER_NOT_FOUND: "Substitute teacher not found",
    LESSON_NOT_FOUND: "Lesson not found",
  },
  vi: {
    GENERATED: "Tạo lịch học thành công",
    UPDATED: "Cập nhật lịch học thành công",
    DELETED: "Xóa lịch học thành công",
    BULK_DELETED: "Đã xóa tất cả lịch học của khóa học",
    NOT_FOUND: "Không tìm thấy lịch học",
    LIST_SUCCESS: "Lấy danh sách lịch học thành công",
    DETAIL_SUCCESS: "Lấy thông tin lịch học thành công",
    COURSE_NOT_FOUND: "Không tìm thấy khóa học để tạo lịch",
    TEACHER_SCHEDULE_SUCCESS: "Lấy lịch dạy của giáo viên thành công",
    INVALID_WEEK_DAYS: "Ngày trong tuần không hợp lệ",
    INVALID_TIME_RANGE: "Giờ bắt đầu phải trước giờ kết thúc",
    NO_SCHEDULES_GENERATED: "Không tạo được lịch học - kiểm tra khoảng thời gian và ngày trong tuần",
    TEACHER_PERMISSION_DENIED: "Bạn chỉ được sửa lịch học của khóa học mình dạy",
    SUBSTITUTE_TEACHER_NOT_FOUND: "Không tìm thấy giáo viên thay thế",
    LESSON_NOT_FOUND: "Không tìm thấy bài học",
  },
};
