// Vietnamese Response Messages
module.exports = {
  AUTH: {
    REGISTER_SUCCESS: "Đăng ký người dùng thành công",
    LOGIN_SUCCESS: "Đăng nhập thành công",
    LOGOUT_SUCCESS: "Đăng xuất thành công",
    PROFILE_RETRIEVED: "Lấy thông tin hồ sơ thành công",
    PROFILE_UPDATED: "Cập nhật hồ sơ thành công",
    PASSWORD_CHANGED: "Đổi mật khẩu thành công",
    INVALID_CREDENTIALS: "Email hoặc mật khẩu không đúng",
    EMAIL_ALREADY_EXISTS: "Email đã tồn tại",
    ACCOUNT_DEACTIVATED: "Tài khoản đã bị vô hiệu hóa. Vui lòng liên hệ quản trị viên.",
    VALIDATION_ERROR: "Lỗi xác thực",
    ROLE_REQUIRED: "Vai trò là bắt buộc",
    PASSWORD_TOO_SHORT: "Mật khẩu phải có ít nhất 8 ký tự",
    PASSWORD_MUST_DIFFER: "Mật khẩu mới phải khác mật khẩu hiện tại",
    CURRENT_PASSWORD_INCORRECT: "Mật khẩu hiện tại không đúng",
    USER_NOT_FOUND: "Không tìm thấy người dùng",
    CANNOT_REGISTER_AS_ADMIN: "Không thể đăng ký với vai trò admin",
    EMAIL_PASSWORD_REQUIRED: "Email và mật khẩu là bắt buộc",
  },
  COMMON: {
    SUCCESS: "Thao tác thành công",
    CREATED: "Tạo tài nguyên thành công",
    UPDATED: "Cập nhật tài nguyên thành công",
    DELETED: "Xóa tài nguyên thành công",
    NOT_FOUND: "Không tìm thấy tài nguyên",
    UNAUTHORIZED: "Truy cập không được phép",
    FORBIDDEN: "Bị cấm truy cập",
    INTERNAL_SERVER_ERROR: "Lỗi máy chủ nội bộ",
    VALIDATION_ERROR: "Lỗi xác thực",
    INVALID_TOKEN: "Token không hợp lệ hoặc đã hết hạn",
  },
};
